# Generated by Django 2.1.7 on 2022-04-21 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220421_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 21, 15, 14, 36, 345924)),
        ),
    ]
